import { execa } from 'execa';
import type { ResolvedTask } from '../plan/schema/types.js';
import type { PrSubmitter } from './orchestrator.js';

export interface GhPrSubmitterOptions {
  rootDir: string;
  baseBranch: string;
  remote?: string;
  draft?: boolean;
  bin?: string;
  /** Plan name + run id, baked into the PR body. */
  planName: string;
  runId: string;
}

/**
 * PrSubmitter that pushes the task branch and creates a PR via `gh pr create`.
 * Idempotent: if a PR already exists for the branch, it returns the URL without
 * creating a duplicate.
 */
export class GhPrSubmitter implements PrSubmitter {
  constructor(private readonly opts: GhPrSubmitterOptions) {}

  async submit(task: ResolvedTask, branch: string): Promise<{ url?: string; error?: string }> {
    const bin = this.opts.bin ?? 'gh';
    const remote = this.opts.remote ?? 'origin';

    // Confirm gh is authenticated (matches the F4.4 probe shape).
    const auth = await execa(bin, ['auth', 'status'], { cwd: this.opts.rootDir, reject: false });
    if (typeof auth.exitCode !== 'number' || auth.exitCode !== 0) {
      return { error: 'gh is not authenticated; run `gh auth login`' };
    }

    // Push the branch (with --set-upstream the first time).
    const push = await execa('git', ['push', '-u', remote, branch], {
      cwd: this.opts.rootDir,
      reject: false,
    });
    if (typeof push.exitCode !== 'number' || push.exitCode !== 0) {
      return {
        error: `git push ${remote} ${branch} failed: ${push.stderr?.toString() ?? '(no stderr)'}`,
      };
    }

    // Existing PR?
    const view = await execa(bin, ['pr', 'view', branch, '--json', 'url,state'], {
      cwd: this.opts.rootDir,
      reject: false,
    });
    if (typeof view.exitCode === 'number' && view.exitCode === 0) {
      try {
        const parsed = JSON.parse(view.stdout?.toString() ?? '{}') as { url?: string; state?: string };
        if (parsed.url && parsed.state === 'OPEN') {
          return { url: parsed.url };
        }
      } catch {
        // ignore — fall through to create
      }
    }

    const args = [
      'pr',
      'create',
      '--base',
      this.opts.baseBranch,
      '--head',
      branch,
      '--title',
      `[yaao] ${task.title}`,
      '--body',
      buildPrBody(task, this.opts.planName, this.opts.runId),
    ];
    if (this.opts.draft) args.push('--draft');
    const create = await execa(bin, args, { cwd: this.opts.rootDir, reject: false });
    if (typeof create.exitCode !== 'number' || create.exitCode !== 0) {
      return {
        error: `gh pr create failed: ${create.stderr?.toString() ?? '(no stderr)'}`,
      };
    }
    const url = (create.stdout?.toString() ?? '').trim();
    return { url };
  }
}

export function buildPrBody(task: ResolvedTask, planName: string, runId: string): string {
  return [
    `Generated by yaao for task \`${task.id}\` (run \`${runId}\`).`,
    '',
    `**Plan**: \`${planName}\``,
    `**Agent**: \`${task.agent}\`${task.model ? ` (\`${task.model}\`)` : ''}`,
    '',
    '## Summary',
    '',
    task.description ?? task.title,
    '',
    task.depends.length > 0
      ? `## Linked tasks\n\nDepends on: ${task.depends.map((d) => `\`${d}\``).join(', ')}`
      : '',
  ]
    .filter(Boolean)
    .join('\n');
}
